### ISSUE TITLE
Save dialog window for each file?

### ISSUE THREAD

**Issue by mcrogers78** [elliot-labs/Shutterfly-Bulk-Downloader#2]
Hi There - I am trying to use the extension, and I am getting a window to save each individual file when i run the extension.  Is there any way to avoid this?  I have a couple thousand files I want to download and clicking save for each one is not my preferred option.  

Thanks!

**Comment by elliot-huffman** [comment]
Hi @mcrogers78 This plugin does not create a save window, it passes the picture to google chrome's download manager.

You would want to disable the chrome setting that asks where to save the file. By default it is off. See the picture.

The setting is in the advanced section.
![screenshot 15](https://cloud.githubusercontent.com/assets/5030490/23285263/0f979c9a-f9fe-11e6-8879-f0c9e46a0743.png)

Also shutterfly just updated their site and the plugin is not catching the selected pictures. I am going to create a separate issue for that problem.

**Comment by mcrogers78** [comment]
Great - thanks much for the help.  I really hope you can update the
extension, since I think it's incredibly helpful.  Thanks!!!!

- Matt Rogers
